{-# LANGUAGE DataKinds         #-}
{-# LANGUAGE DeriveGeneric     #-}
{-# LANGUAGE DeriveTraversable #-}
{-# LANGUAGE FlexibleContexts  #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE GADTs             #-}
{-# LANGUAGE KindSignatures    #-}
{-# LANGUAGE LambdaCase        #-}
{-# LANGUAGE PatternSynonyms   #-}
{-# LANGUAGE RankNTypes        #-}
{-# LANGUAGE TemplateHaskell   #-}
{-# LANGUAGE TypeFamilies      #-}
{-# OPTIONS_GHC -Wno-missing-signatures -Wno-redundant-constraints -Wno-orphans #-}
-- | Scope-safe lambda-let syntax, generated by free-foil's Template Haskell
-- from "LambdaLet.Raw": the signature @TermSig@, the term type @FFTerm@, the
-- pattern synonyms @FFApp@, @FFLam@ and @FFLet@, and the conversions
-- @toTerm@ and @fromTerm@.
module LambdaLet.Generated where

import qualified Control.Monad.Foil as Foil
import Control.Monad.Free.Foil (AST)
import Control.Monad.Free.Foil.TH.MkFreeFoil
import Data.Bifunctor.TH
import Data.ZipMatchK
import Generics.Kind.TH (deriveGenericK)

import LambdaLet.Raw
import LambdaLet.Syntax.Print (printTree)

mkFreeFoil config

deriveGenericK ''FFPattern
instance Foil.SinkableK FFPattern
instance Foil.HasNameBinders FFPattern
instance Foil.UnifiablePattern FFPattern

deriveBifunctor ''TermSig
deriveBifoldable ''TermSig
deriveBitraversable ''TermSig

deriveGenericK ''TermSig
instance ZipMatchK VarIdent where zipMatchWithK = zipMatchViaEq
instance ZipMatchK TermSig

mkFreeFoilConversions config

-- | Terms print through the raw conversion and BNFC's printer. Variables are
-- named by foil identifier, so the output re-parses but is not α-canonical.
instance Show (AST FFPattern TermSig n) where
  show = printTree . fromTerm
