{-# LANGUAGE DataKinds #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE RankNTypes #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# OPTIONS_GHC -Wno-orphans #-}

-- | Parsing lambda-let terms from strings, so that examples and tests can be
-- written as string literals.
--
-- The lexer and parser are generated by BNFC from
-- @demo/grammar/LambdaLet/Syntax.cf@ (module "LambdaLet.Syntax.Par"); scope
-- resolution into free-foil syntax is generated by free-foil's Template
-- Haskell ('toTerm', via 'resolve'). Nothing here is hand-written except the
-- thin glue.
--
-- Concrete syntax: application by juxtaposition (left-associative), @\\x. t@
-- for lambda, and @let x = e in t@ for let (the body extends as far right as
-- possible).
--
-- 'fromString' (the 'IsString' instance) parses a __closed__ term; a term with
-- free variables throws when resolved. Use 'parseOpen' for terms in a
-- non-empty scope.
module LambdaLet.Parser
  ( parseLambdaLet
  , parseOpen
  , resolve
  , withFreeVars
  ) where

import Data.String (IsString (..))
import Data.Map.Strict (Map)
import qualified Data.Map.Strict as Map

import FreeFoil.NbE
  ( Name, Scope, S (VoidS), Distinct, DistinctEvidence (Distinct)
  , assertDistinct, emptyScope, extendScope, nameOf, sink, withFresh
  )
import LambdaLet (LambdaLet)
import LambdaLet.Generated (toTerm)
import LambdaLet.Syntax.Abs (Term, VarIdent (..))
import LambdaLet.Syntax.Par (myLexer, pTerm)

-- | Resolve a raw named term into scope-safe syntax using free-foil's generated
-- conversion. Free variables must be present in the environment; otherwise
-- 'toTerm' throws.
resolve :: Distinct n => Scope n -> Map String (Name n) -> Term -> LambdaLet n
resolve scope env = toTerm scope (Map.mapKeys VarIdent env)

-- | Parse a raw term with the BNFC-generated lexer and parser.
parseRaw :: String -> Either String Term
parseRaw = pTerm . myLexer

-- | Parse a closed lambda-let term.
parseLambdaLet :: String -> Either String (LambdaLet VoidS)
parseLambdaLet s = resolve emptyScope Map.empty <$> parseRaw s

-- | Parse a term in a given scope, with an environment mapping the names of the
-- free variables that are already in scope.
parseOpen :: Distinct n => Scope n -> Map String (Name n) -> String -> Either String (LambdaLet n)
parseOpen scope env s = resolve scope env <$> parseRaw s

instance IsString (LambdaLet VoidS) where
  fromString = either (error . ("LambdaLet.Parser: " ++)) id . parseLambdaLet

-- | Run a continuation in a scope extended with the given free variable names,
-- providing the name environment that maps each to its fresh 'Name'. Later
-- names shadow earlier ones. Useful for working with open terms (neutrals).
withFreeVars
  :: Distinct n
  => Scope n
  -> Map String (Name n)
  -> [String]
  -> (forall l. Distinct l => Scope l -> Map String (Name l) -> r)
  -> r
withFreeVars scope env [] k = k scope env
withFreeVars scope env (x : xs) k =
  withFresh scope $ \binder ->
    case assertDistinct binder of
      Distinct ->
        let env' = Map.insert x (nameOf binder) (Map.map sink env)
        in withFreeVars (extendScope binder scope) env' xs k
