{-# LANGUAGE BangPatterns    #-}
{-# LANGUAGE DataKinds       #-}
{-# LANGUAGE GADTs           #-}
{-# LANGUAGE KindSignatures  #-}
{-# LANGUAGE LambdaCase      #-}
{-# LANGUAGE RankNTypes      #-}
{-# LANGUAGE TemplateHaskell #-}
-- | Lambda-pi NbE with a value type generated by "FreeFoil.NbE.TH". The
-- splice generates 'Val', one constructor per constructor of @TermSig@, and
-- 'eval', 'evalNode', 'quote' and 'nfCodegen'; the language writes only
-- 'evalSig', its one elimination rule. The result is the NbE of
-- "LambdaPi.Monomorphic": the same syntax, algorithm and value type.
module LambdaPi.Codegen
  ( Val (..)
  , eval
  , evalSig
  , evalNode
  , quote
  , nfCodegen
  ) where

import Control.Monad.Foil
import Control.Monad.Free.Foil

import FreeFoil.NbE.TH (ValueConfig (..), defaultValueConfig, mkValue)
import LambdaPi.Generated (FFPattern (..), FFTerm, TermSig (..))

$(mkValue (defaultValueConfig ''TermSig ''FFPattern) { valueNfName = "nfCodegen" })

-- | The one elimination rule, application. A lambda is entered under its
-- environment extended with the (lazy) argument; a neutral head gives a
-- stuck application. Every other node is an introduction form.
evalSig :: Substitution Val i o -> TermSig (ScopedAST FFPattern TermSig i) (FFTerm i) -> Val o
evalSig env = \case
  AppSig fun arg ->
    case eval env fun of
      VLam env' binder body -> eval (addSubst env' binder (eval env arg)) body
      fun' -> VApp fun' (eval env arg)
  node -> evalNode env node
