{-# LANGUAGE BangPatterns    #-}
{-# LANGUAGE DataKinds       #-}
{-# LANGUAGE GADTs           #-}
{-# LANGUAGE KindSignatures  #-}
{-# LANGUAGE LambdaCase      #-}
{-# LANGUAGE RankNTypes      #-}
{-# LANGUAGE TemplateHaskell #-}
-- | Lambda-pi NbE generated by "FreeFoil.NbE.TH" with whole patterns in the
-- values ('valueUnpackBinder' off), as for a binder type that is not a single
-- variable. It exercises the generator's general path for binders, which
-- "LambdaPi.Codegen" does not use, in the tests and benchmarks.
module LambdaPi.CodegenPattern
  ( nfPattern
  ) where

import Control.Monad.Foil
import Control.Monad.Free.Foil

import FreeFoil.NbE.TH (ValueConfig (..), defaultValueConfig, mkValue)
import LambdaPi.Generated (FFPattern (..), FFTerm, TermSig (..))

$(mkValue (defaultValueConfig ''TermSig ''FFPattern)
    { valueNfName = "nfPattern", valueUnpackBinder = False })

-- | Application, as in "LambdaPi.Codegen", with the binder inside its pattern.
evalSig :: Substitution Val i o -> TermSig (ScopedAST FFPattern TermSig i) (FFTerm i) -> Val o
evalSig env = \case
  AppSig fun arg ->
    case eval env fun of
      VLam env' (FFPatternVar binder) body -> eval (addSubst env' binder (eval env arg)) body
      fun' -> VApp fun' (eval env arg)
  node -> evalNode env node
