{-# LANGUAGE DataKinds #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE RankNTypes #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# OPTIONS_GHC -Wno-orphans #-}

-- | Parsing lambda-pi terms from strings, so that examples and tests can be
-- written as string literals.
--
-- The lexer and parser are generated by BNFC from @demo/grammar/Syntax.cf@
-- (module "LambdaPi.Syntax.Par"); scope resolution into free-foil syntax is
-- generated by free-foil's Template Haskell ('toTerm', via 'resolve'). Nothing
-- here is hand-written except the thin glue.
--
-- Concrete syntax: application by juxtaposition (left-associative), @\\x. t@ for
-- lambda, and @(x : A) -> B@ for the dependent function type. A non-dependent
-- function type is written with an unused binder, e.g. @(x : A) -> B@ where @B@
-- does not mention @x@.
--
-- 'fromString' (the 'IsString' instance) parses a __closed__ term; a term with
-- free variables throws when resolved. Use 'parseOpen' for terms in a non-empty
-- scope.
module LambdaPi.Parser
  ( parseLambdaPi
  , parseOpen
  , resolve
  , withFreeVars
  ) where

import Data.String (IsString (..))
import Data.Map.Strict (Map)
import qualified Data.Map.Strict as Map

import FreeFoil.NbE
  ( Name, Scope, S (VoidS), Distinct, DistinctEvidence (Distinct)
  , assertDistinct, emptyScope, extendScope, nameOf, sink, withFresh
  )
import LambdaPi (LambdaPi)
import LambdaPi.Generated (toTerm)
import LambdaPi.Syntax.Abs (Term, VarIdent (..))
import LambdaPi.Syntax.Par (myLexer, pTerm)

-- | Resolve a raw named term into scope-safe syntax using free-foil's generated
-- conversion. Free variables must be present in the environment; otherwise
-- 'toTerm' throws.
resolve :: Distinct n => Scope n -> Map String (Name n) -> Term -> LambdaPi n
resolve scope env = toTerm scope (Map.mapKeys VarIdent env)

-- | Parse a raw term with the BNFC-generated lexer and parser.
parseRaw :: String -> Either String Term
parseRaw = pTerm . myLexer

-- | Parse a closed lambda-pi term.
parseLambdaPi :: String -> Either String (LambdaPi VoidS)
parseLambdaPi s = resolve emptyScope Map.empty <$> parseRaw s

-- | Parse a term in a given scope, with an environment mapping the names of the
-- free variables that are already in scope.
parseOpen :: Distinct n => Scope n -> Map String (Name n) -> String -> Either String (LambdaPi n)
parseOpen scope env s = resolve scope env <$> parseRaw s

instance IsString (LambdaPi VoidS) where
  fromString = either (error . ("LambdaPi.Parser: " ++)) id . parseLambdaPi

-- | Run a continuation in a scope extended with the given free variable names,
-- providing the name environment that maps each to its fresh 'Name'. Later
-- names shadow earlier ones. Useful for working with open terms (neutrals).
withFreeVars
  :: Distinct n
  => Scope n
  -> Map String (Name n)
  -> [String]
  -> (forall l. Distinct l => Scope l -> Map String (Name l) -> r)
  -> r
withFreeVars scope env [] k = k scope env
withFreeVars scope env (x : xs) k =
  withFresh scope $ \binder ->
    case assertDistinct binder of
      Distinct ->
        let env' = Map.insert x (nameOf binder) (Map.map sink env)
        in withFreeVars (extendScope binder scope) env' xs k
