{-# LANGUAGE TemplateHaskell #-}

-- | The 'FreeFoilConfig' that drives free-foil's Template Haskell generation of
-- the scope-safe types, pattern synonyms, and conversions.
--
-- The raw (named, un-scoped) syntax itself — @Term@, @Pattern@, @ScopedTerm@,
-- @VarIdent@ — is generated by BNFC from @demo/grammar/Syntax.cf@ (module
-- "LambdaPi.Syntax.Abs"); this module only re-exports it and supplies the small
-- helpers and config that free-foil needs.
--
-- The config lives in its own module because Template Haskell may not splice a
-- value defined in the same module where it is used.
module LambdaPi.Raw
  ( module LambdaPi.Syntax.Abs
  , config
  , rawVar
  , intToVarIdent
  , rawScopedTerm
  , rawScopeToTerm
  ) where

import Control.Monad.Free.Foil.TH.MkFreeFoil (FreeFoilConfig (..), FreeFoilTermConfig (..))

import LambdaPi.Syntax.Abs

rawVar :: VarIdent -> Term
rawVar = Var

intToVarIdent :: Int -> VarIdent
intToVarIdent i = VarIdent ("x" <> show i)

rawScopedTerm :: Term -> ScopedTerm
rawScopedTerm = AScopedTerm

rawScopeToTerm :: ScopedTerm -> Term
rawScopeToTerm (AScopedTerm t) = t

config :: FreeFoilConfig
config = FreeFoilConfig
  { rawQuantifiedNames = []
  , freeFoilTermConfigs =
      [ FreeFoilTermConfig
          { rawIdentName = ''VarIdent
          , rawTermName = ''Term
          , rawBindingName = ''Pattern
          , rawScopeName = ''ScopedTerm
          , rawVarConName = 'Var
          , rawSubTermNames = []
          , rawSubScopeNames = []
          , intToRawIdentName = 'intToVarIdent
          , rawVarIdentToTermName = 'rawVar
          , rawTermToScopeName = 'rawScopedTerm
          , rawScopeToTermName = 'rawScopeToTerm
          } ]
  , freeFoilNameModifier = ("FF" ++)
  , freeFoilScopeNameModifier = ("FFScoped" ++)
  , freeFoilConNameModifier = ("FF" ++)
  , freeFoilConvertFromName = ("from" ++)
  , freeFoilConvertToName = ("to" ++)
  , signatureNameModifier = (++ "Sig")
  }
