{-# LANGUAGE TemplateHaskell #-}
-- | The raw syntax generated by BNFC from @demo/grammar/LambdaPi/Syntax.cf@,
-- re-exported together with the helpers and the 'FreeFoilConfig' that
-- free-foil's Template Haskell needs. The config lives in a module of its own
-- because a splice cannot use a value defined in the same module.
module LambdaPi.Raw
  ( module LambdaPi.Syntax.Abs
  , config
  , rawVar
  , intToVarIdent
  , rawScopedTerm
  , rawScopeToTerm
  ) where

import Control.Monad.Free.Foil.TH.MkFreeFoil (FreeFoilConfig (..), FreeFoilTermConfig (..))

import LambdaPi.Syntax.Abs

rawVar :: VarIdent -> Term
rawVar = Var

intToVarIdent :: Int -> VarIdent
intToVarIdent i = VarIdent ("x" <> show i)

rawScopedTerm :: Term -> ScopedTerm
rawScopedTerm = AScopedTerm

rawScopeToTerm :: ScopedTerm -> Term
rawScopeToTerm (AScopedTerm t) = t

config :: FreeFoilConfig
config = FreeFoilConfig
  { rawQuantifiedNames = []
  , freeFoilTermConfigs =
      [ FreeFoilTermConfig
          { rawIdentName = ''VarIdent
          , rawTermName = ''Term
          , rawBindingName = ''Pattern
          , rawScopeName = ''ScopedTerm
          , rawVarConName = 'Var
          , rawSubTermNames = []
          , rawSubScopeNames = []
          , intToRawIdentName = 'intToVarIdent
          , rawVarIdentToTermName = 'rawVar
          , rawTermToScopeName = 'rawScopedTerm
          , rawScopeToTermName = 'rawScopeToTerm
          } ]
  , freeFoilNameModifier = ("FF" ++)
  , freeFoilScopeNameModifier = ("FFScoped" ++)
  , freeFoilConNameModifier = ("FF" ++)
  , freeFoilConvertFromName = ("from" ++)
  , freeFoilConvertToName = ("to" ++)
  , signatureNameModifier = (++ "Sig")
  }
